name: Deploy to Firebase Hosting on main branch

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - run: npm install
      - run: npm run build 
      
      - run: npm install -g firebase-tools
      - run: firebase deploy --only hosting:samir --project portfol-a9eae
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
